language: python

sudo: false

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO='django>=1.8.0,<1.9.0'
  - DJANGO='django>=1.9.0,<1.10.0'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install $DJANGO
  - pip install -e .
script:
  - make test
notifications:
  email: false
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.2"
      env: DJANGO='django>=1.9.0,<1.10.0'
    - python: "3.3"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.3"
      env: DJANGO='django>=1.9.0,<1.10.0'
    - python: "3.4"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.5"
      env: DJANGO='django>=1.7.0,<1.8.0'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
after_success:
  - bash <(curl -s https://codecov.io/bash)
