language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO='django>=1.4.0,<1.5.0'
  - DJANGO='django>=1.5.0,<1.6.0'
  - DJANGO='django>=1.6.0,<1.7.0'
  - DJANGO='django>=1.7.0,<1.8.0'
  - DJANGO='django>=1.8.0,<1.9.0'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install $DJANGO
  - pip install "file://`pwd`#egg=django-crispy-forms[tests]"
  - pip install -e . --use-mirrors
script:
  - make test
notifications:
  email: false
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO='django>=1.4.0,<1.5.0'
    - python: "3.3"
      env: DJANGO='django>=1.4.0,<1.5.0'
    - python: "3.4"
      env: DJANGO='django>=1.4.0,<1.5.0'
    - python: "2.6"
      env: DJANGO='django>=1.7.0,<1.8.0'
    - python: "2.6"
      env: DJANGO='django>=1.8.0,<1.9.0'
    - python: "2.6"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
