language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install Django==$DJANGO
  - pip install "file://`pwd`#egg=django-crispy-forms[tests]"
  - pip install -e . --use-mirrors
script: cd crispy_forms/tests && python runtests.py
notifications:
  email: false
env:
  - DJANGO=1.2.7
  - DJANGO=1.3
  - DJANGO=1.3.1
  - DJANGO=1.3.2
  - DJANGO=1.3.3
  - DJANGO=1.3.4
  - DJANGO=1.3.5
  - DJANGO=1.3.7
  - DJANGO=1.4
  - DJANGO=1.4.1
  - DJANGO=1.4.2
  - DJANGO=1.4.3
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.1
