language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO='django>=1.8.0,<1.9.0'
  - DJANGO='django>=1.11.0,<2.0'
  - DJANGO='django>=2.0,<2.1'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
before_install:
  - pip install --upgrade 'pytest<3.0.0'
install:
  - pip install $DJANGO
  - pip install -e .
script:
  - make test
notifications:
  email: false
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "2.7"
      env: DJANGO='django>=2.0,<2.1'
    - python: "3.4"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.7-dev"
      env: DJANGO='django>=1.8.0,<1.9.0'
    - python: "3.7-dev"
      env: DJANGO='django>=1.11.0,<2.0'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.7-dev"
after_success:
  - bash <(curl -s https://codecov.io/bash)
